---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services


# - Want to join the Epsilon A&R team?:
#     - 🎧 Start Here:
#         href: https://epsilonrecords.nl/anr
#         description: Submit your professional details and set up your profile as a new A&R representative in the company's online portal.
- Artist Onboarding:
    - Submit a New Artist Profile:
        href: https://epsilonrecords.nl/profile
        description: Use this portal to submit and update new artist profiles within the company's system.
    - Submit Audio Files & Media Assets:
        href: https://epsilonrecords.nl/submit
        description: The audio file and media assets Submission Portal is a secure online platform where A&R reps can upload high-quality tracks and related media content for their artists' upcoming releases. Maximum transfer size is 200GB.
- A&R Team:
    - Events & Release Calendar:
        href: https://epsilonrecords.nl/calendar
        description: The events & release calendar is a centralized scheduling tool that keeps track of all industry events, release dates, and deadlines crucial for the planning and coordination of Artist and Repertoire activities.
    - Production Review Board:
        href: https://epsilonrecords.nl/review
        description: The production review board serves as a dedicated platform for the A&R team to evaluate, provide feedback on, and review the incoming tracks from artists and producers.
    - Book a Meeting:
        href: https://epsilonrecords.nl/book
        description: Utilize our online booking system to conveniently schedule a meeting with the team, ensuring a collaborative approach to address your needs or project discussions.
- Internal Tools:
    - Artist Relationship Management (CRM):
        href: https://epsilonrecords.pipedrive.com
        description: Pipedrive streamlines our A&R processes, serving as a robust CRM system that optimizes the management of artist relations, client contact info, and project pipelines.
    - Company Email Login:
        href: https://gmail.com
        description: Access your official @epsilonrecords.com company email account to stay updated on communications and A&R activities.
    - Industry Contact List:
        href: https://epsilonrecords.nl/contacts
        description: Our industry contact list is a curated directory offering A&R professionals access to a network of valuable music industry connections, including publishers, producers, and other key stakeholders.
- Label Community:
    - Epsilon Records Music Report:
        href: https://epsilon.report
        description: Sign up to receive the monthly Epsilon Records Music Report for regular insights and updates on our business performance and initiatives.
    - Instagram @epsilonrecords:
        href: https://instagram.com/epsilonrecords
        description: Follow our Instagram @epsilonrecords to keep up with the latest news, behind-the-scenes content, and interact with our vibrant music community.
- Benefits:
    - Remote Work:
        description: Embrace the flexibility of remote work, allowing you to collaborate and create from wherever you find inspiration.
    - Flexible Working Hours:
        description: Take control of your workday with flexible working hours, designed to fit your personal schedule and maximize your productivity.
    # - Affordable Health Insurance:
    #     href: https://safetywing.com
    #     description: We have partnered with SafetyWing to provide our remote team with access to affordable health insurance, ensuring you're covered wherever you work.
    # - Annual Company Retreat:
    #     description: Our annual company offsite retreat focuses on team-building and relaxation, providing a chance to strengthen connections with colleagues in a refreshing and dynamic setting.
- Perks:
    - Epsilon Merch Shop Discount (25% off):
        href: https://epsilonrecords.nl/merch
        description: Take advantage of your 25% staff discount at the Epsilon Merch Shop, a benefit to appreciate our A&R team's dedication and hard work.
    # - TravelPerk Booking Deals:
    #     href: https://travelperk.com
    #     description: TravelPerk offers our A&R representatives a streamlined and flexible platform for booking and managing artist travel, ensuring they can focus on discovering talent without the hassle of travel logistics.
    - Outsite Accomodation Deals:
        href: https://outsite.co
        description: Enjoy special discounted accommodations through our partnership with Outsite, ideal for remote work getaways that combine the tranquility of nature with the comforts of a well-appointed workspace.
- Support:
    # - Open a Support Ticket:
    #     href: https://support.epsilonrecords.nl
    #     description: For assistance, Epsilon Support offers a helpdesk where you can open a ticket for any issues or inquiries, ensuring you receive the necessary support in a timely manner.
    - Browse the FAQ:
        href: https://epsilonrecords.nl/faq
        description: Explore our comprehensive FAQ section to find quick answers to common questions and gain clearer insights into the A&R processes and best practices.
    - System Status:
        href: https://epsilon.fail
        description: The Epsilon Records Technologies Systems Status page offers real-time updates on the performance and availability of our services, ensuring transparency and reliability for our users.
- Resources:
    - A&R Onboarding Guide:
        href: https://epsilonrecords.nl/anr-guide
        description: The A&R Onboarding Guide is a detailed resource designed to orient and educate new A&R representatives on the policies, procedures, and expectations of their role within the music industry organization.
    - Artist Onboarding Guide:
        href: https://epsilonrecords.nl/onboarding
        description: The Artist Onboarding Guide is a comprehensive manual that provides newly signed artists with step-by-step instructions and essential information to seamlessly integrate into the label or agency's processes and community.
