---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services


- Want to join the Epsilon A&R team?:
    - Start Here 🎧:
        href: https://epsilonrecords.nl/anr
        description: Submit your professional details and set up your profile as a new A&R representative in the company's online portal.
    - A&R Onboarding Guide:
        href: https://epsilonrecords.nl/anr-guide
        description: The A&R Onboarding Guide is a detailed resource designed to orient and educate new A&R representatives on the policies, procedures, and expectations of their role within the music industry organization.
- Artist Onboarding:
    - Submit a New Artist Profile:
        href: https://epsilonrecords.nl/profile
        description: Use this portal to submit and update new artist profiles within the company's system.
    - Artist Onboarding Guide:
        href: https://epsilonrecords.nl/onboarding
        description: The Artist Onboarding Guide is a comprehensive manual that provides newly signed artists with step-by-step instructions and essential information to seamlessly integrate into the label or agency's processes and community.
    - Submit Audio Files & Media Assets:
        href: https://epsilonrecords.nl/submit
        description: The A&R Mastered Audio Files and Media Assets Submission Portal is a secure online platform where A&R reps can upload high-quality tracks and related media content for their artists' upcoming releases. Maximum transfer size is 200GB.
- A&R Team:
    - A&R Meetings & Events Calendar:
        href: https://epsilonrecords.nl/calendar
        description: The A&R team calendar is a centralized scheduling tool that keeps track of all industry events, release dates, and deadlines crucial for the planning and coordination of Artist and Repertoire activities.
    - Weekly Music Review Zoom Call:
        href: https://eu01web.zoom.us/j/68447707558?pwd=YzEzQS8rbWtGOFB4UExDVmdpTUZ5Zz09
        description: Participate in our Weekly Music Review Zoom Call every Sunday from 16:00 to 18:00 CET to discuss new finds and industry trends.
    - Book a New A&R Meeting:
        href: https://epsilonrecords.nl/book
        description: Utilize our online booking system to conveniently schedule a meeting with the team, ensuring a collaborative approach to address your needs or project discussions.
- Internal Tools:
    - Manage Artist Relations (CRM):
          href: https://epsilonrecords.pipedrive.com
          description: Pipedrive streamlines our A&R processes, serving as a robust CRM system that optimizes the management of artist relations, contact info, and project pipelines.
    - A&R Production Review Board:
        href: https://epsilonrecords.nl/review
        description: The A&R Production Review Board serves as a dedicated platform for the A&R team to evaluate, provide feedback on, and review the incoming tracks from artists and producers.
    - Curate the Epsilon Spotify Playlist:
          href: https://open.spotify.com/playlist/3V3NcVTRCHomITtmWLb86I?si=bce0b3a658e547bc&pt=a1f62f35e8ac8c516062f53507381745
          description: Collaborate with fellow Epsilon team members to craft and continuously update our signature Spotify playlist that highlights our curated selection of artists and trending tracks.
    - Send & Manage Contracts:
          href: https://app.docusign.com/auth
          description: We leverage DocuSign to effortlessly send and manage artist contacts, ensuring secure and efficient digital signatures for seamless communication and record-keeping.
    - Company Email Login:
        href: https://mail.epsilonrecords.com
        description: Access your official company email account to stay updated on communications and A&R activities.
    - Company Slack Login:
        href: https://epsilon-records.slack.com
        description: Utilize the company Slack channel for real-time messaging, collaboration, and updates within our A&R team.
- Label Community:
    - Epsilon Records Music Report:
        href: https://epsilon.report
        description: Sign up to receive the monthly Epsilon Records Music Report for regular insights and updates on our business performance and initiatives.
    - Epsilon Records Discord:
        href: https://discord.gg/ek55B8wGqE
        description: Connect with the team and our label fans by joining our Company Discord server for daily discussions and community engagement
    - Instagram Engagement:
        href: https://instagram.com/epsilonrecords
        description: Follow our Instagram @epsilonrecords to keep up with the latest news, behind-the-scenes content, and interact with our vibrant music community.
- Benefits:
    - Remote Work:
        description: Embrace the flexibility of remote work, allowing you to collaborate and create from wherever you find inspiration.
    - Flexible Working Hours:
        description: Take control of your workday with flexible working hours, designed to fit your personal schedule and maximize your productivity.
    - Affordable Health Insurance:
        href: https://safetywing.com
        description: We have partnered with SafetyWing.com to provide our remote team with access to affordable health insurance, ensuring you're covered wherever you work.
    - Annual Company Retreat:
        description: Our annual company retreat focuses on team-building and relaxation, providing a chance to strengthen connections with colleagues in a refreshing and dynamic setting.
- Perks:
    - Epsilon.gifts Shop Discount (25% off):
        href: https://epsilon.gifts
        description: Take advantage of your 25% staff discount at the Epsilon Gift Shop with code 'ANR2024', a benefit to appreciate our A&R team's dedication and hard work.
    - TravelPerk.com Booking Deals:
        href: https://travelperk.com
        description: TravelPerk offers our A&R representatives a streamlined and flexible platform for booking and managing artist travel, ensuring they can focus on discovering talent without the hassle of travel logistics.
    - Outsite.co Accomodation Deals:
        href: https://outsite.co
        description: Enjoy special discounted accommodations through our partnership with Outside, ideal for remote work getaways that combine the tranquility of nature with the comforts of a well-appointed workspace.
- Support & Resources:
    - Open a Support Ticket:
        href: https://support.epsilonrecords.nl
        description: For assistance, Epsilon Support offers a helpdesk where you can open a ticket for any issues or inquiries, ensuring you receive the necessary support in a timely manner.
    - Browse the FAQ:
        href: https://epsilonrecords.nl/faq
        description: Explore our comprehensive FAQ section to find quick answers to common questions and gain clearer insights into the A&R processes and best practices.
    - Industry Contact List:
        href: https://epsilonrecords.nl/contacts
        description: Our A&R industry contact list is a curated directory offering A&R professionals access to a network of valuable music industry connections, including publishers, producers, and other key stakeholders.

