---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services


- Want to join the Epsilon A&R team?:
    - Start Here 🎧:
        href: https://epsilonrecords.nl/anr
        description: Submit your professional details and set up your profile as a new A&R representative in the company's online portal.
    - A&R Onboarding Guide:
        href: https://epsilonrecords.nl/anr-guide
        description: The A&R Onboarding Guide is a detailed resource designed to orient and educate new A&R representatives on the policies, procedures, and expectations of their role within the music industry organization.
- Artist Management:
    - Submit a New Artist Profile:
        href: https://epsilonrecords.nl/profile
        description: Use this portal to submit and update new artist profiles within the company's system.
    - Artist Onboarding Guide:
        href: https://epsilonrecords.nl/onboarding
        description: The Artist Onboarding Guide is a comprehensive manual that provides newly signed artists with step-by-step instructions and essential information to seamlessly integrate into the label or agency's processes and community.
    - Submit Audio Files & Media Assets:
        href: https://epsilonrecords.nl/submit
        description: The A&R Mastered Audio Files and Media Assets Submission Portal is a secure online platform where A&R reps can upload high-quality tracks and related media content for their artists' upcoming releases. Maximum transfer size is 200GB.
- A&R Team:
    - A&R Meetings & Events Calendar:
        href: https://epsilonrecords.nl/calendar
        description: The A&R team calendar is a centralized scheduling tool that keeps track of all industry events, release dates, and deadlines crucial for the planning and coordination of Artist and Repertoire activities.
    - Book a New A&R Meeting:
        href: https://epsilonrecords.nl/book
        description: Utilize our online booking system to conveniently schedule a meeting with the team, ensuring a collaborative approach to address your needs or project discussions.
- Internal Tools:
    - Production Review Board:
        href: https://epsilonrecords.nl/review
        description: The A&R Production Review Board serves as a dedicated platform for the A&R team to evaluate, provide feedback on, and review the incoming tracks from artists and producers.
    - Company Email Login:
        href: https://mail.epsilonrecords.com
        description: Access your official company email account to stay updated on communications and A&R activities.
    - Company Slack:
        href: https://epsilon-records.slack.com
        description: Utilize the company Slack channel for real-time messaging, collaboration, and updates within our A&R team.
- Label Community:
    - Company Report Subscription:
        href: https://epsilon.report
        description: Sign up to receive the Company Report for regular insights and updates on our business performance and initiatives.
    - Company Discord:
        href: https://discord.gg/ek55B8wGqE
        description: Connect with the team and our label fans by joining our Company Discord server for daily discussions and community engagement
- Support & Resources:
    - Open a Support Ticket:
        href: https://support.epsilonrecords.nl
        description: For assistance, Epsilon Support offers a helpdesk where you can open a ticket for any issues or inquiries, ensuring you receive the necessary support in a timely manner.
    - Browse the FAQ:
        href: https://epsilonrecords.nl/faq
        description: Explore our comprehensive FAQ section to find quick answers to common questions and gain clearer insights into the A&R processes and best practices.
    - Industry Contact List:
        href: https://epsilonrecords.nl/contacts
        description: Our A&R industry contact list is a curated directory offering A&R professionals access to a network of valuable music industry connections, including publishers, producers, and other key stakeholders.


