---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Epsilon Records A&R Portal
favicon: https://natehouk.com/files/favicon.ico
color: lime
disableCollapse: true
target: _blank
hideVersion: true
theme: light
base: https://epsilon.careers
layout:
  Want to join the Epsilon A&R team?:
    style: row
    columns: 4